import type { Metadata } from "next"; // 导入 Next.js 的 Metadata 类型，用于类型提示
import { Geist, Geist_Mono } from "next/font/google"; // 从 next/font/google 导入 Geist 和 Geist_Mono 字体
import "./globals.css"; // 引入全局样式

// 配置 Geist Sans 字体
const geistSans = Geist({
  variable: "--font-geist-sans", // 设置字体变量名（注意是两个半角连字符 --）
  subsets: ["latin"],            // 只加载 latin 字符集，减小体积
});

// 配置 Geist Mono 字体
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // 设置字体变量名（注意是两个半角连字符 --）
  subsets: ["latin"],            // 只加载 latin 字符集
});

// 定义全局元数据（SEO用）
export const metadata: Metadata = {
  title: "Create Next App",                // 网页标题
  description: "Generated by create next app", // 网页描述
};

// 根布局组件，包裹所有页面内容
export default function RootLayout({
  children, // 接收所有子组件
}: Readonly<{
  children: React.ReactNode; // children 类型为 React 节点
}>) {
  return (
    <html lang="en"> {/* 设置页面语言为英文 */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // 应用字体变量和抗锯齿效果
      >
        {children} {/* 渲染所有子内容 */}
      </body>
    </html>
  );
}
